name: S.A.N.D CD


on:
  push:
    branches: [ main ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Setup MongoDB
        run: supercharge/mongodb-github-action@1.7.0
          
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
      
      - name: Merge main -> production
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: production
          github_token: ${{ github.token }}