name: S.A.N.D CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Setup MongoDB
        run: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '4.4'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
      