name: S.A.N.D CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Setup MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '4.4'
          
      - name: Create .env file
        run: echo "OPENSEA_API=${{ secrets.OPENSEA_API }}" > .env

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run start:test
        run: npm test
      